### ISSUE TITLE
Use train data as test data?

### ISSUE THREAD

**Issue by traveller59** [healthDataScience/deep-learning-HAR#3]
The offical code in HAR-CNN use "train" folder to generate test data:
```python
X_train, labels_train, list_ch_train = read_data(data_path="./data/", split="train") # train
X_test, labels_test, list_ch_test = read_data(data_path="./data/", split="train") # test
```
When I change them to:
```python
X_train, labels_train, list_ch_train = read_data(data_path="./data/", split="train") # train
X_test, labels_test, list_ch_test = read_data(data_path="./data/", split="test") # test
```
The test accuracy will decrease to 0.877917, not 0.98.

**Comment by bhimmetoglu** [comment]
Good catch! This is a typo and will be corrected...

**Comment by bhimmetoglu** [comment]
Thanks for reporting the problem. 

The code has been fixed and the accuracies have been updated accordingly.

**Comment by guillaume-chevalier** [comment]
@bhimmetoglu I still see the 98% here: 
https://www.datasciencecentral.com/profiles/blogs/time-series-classification-with-tensorflow
It might still be unchanged at other places, too.

**Comment by bhimmetoglu** [comment]
It is not easy (or sometimes possible) to edit websites that publish the blog. The original blog on my website has the corrections. The third party websites has links to the corrected blog as well as the repo, which are corrected. 
 
I added a comment to that site in particular pointing the readers to the corrected versions.
